# Generated by Django 3.2.25 on 2024-06-04 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.categories')),
                ('subcategories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.subcategories')),
            ],
        ),
    ]
